### ISSUE TITLE
Handle case where `toRange()` overruns the text content

### ISSUE THREAD

**Issue by tilgovi** [tilgovi/dom-anchor-text-position#2]

**Comment by kylehalleman** [comment]
Running into this issue with `iter.nextNode()` returning `null`. This is an almost 3 year old issue. I would be happy to submit a PR if you had thoughts on how you were going to deal with this case. Or if you suggest a different or updated library to use that would also be helpful. Thank you.

**Comment by tilgovi** [comment]
I think throwing a `DOMException` with an `DOMException.INDEX_SIZE_ERROR` code would be appropriate.

**Comment by longhotsummer** [comment]
I'm encountering this when working with a position that starts and ends in the same text node, and the end offset is at the end of the text node.

I have worked around it by patching the last block of `textPositionToRange` as in [this commit](https://github.com/laws-africa/indigo/commit/49a24efc60e0409209679abe64bace9ef5140954#diff-00feba2cf9660441f14fa331110a0fa6R238-R246):

```js
if (iter.pointerBeforeReferenceNode) {
  range.setEnd(iter.referenceNode, remainder);
} else {
  // START PATCH
  var node = iter.nextNode();
  if (node) {
    range.setEnd(node, remainder);
  } else {
    range.setEnd(iter.referenceNode, iter.referenceNode.length);
  }
  // END PATCH
}
```
