### ISSUE TITLE
Invalid sourcemaps in transpiled code

### ISSUE THREAD

**Issue by robertknight** [tilgovi/dom-anchor-text-position#3]
The transpiled code in `lib/` includes inline sourcemaps which refer to the original source location in `src/index.js`. However, since `src/` does not exist in the published package, tools which validate sourcemaps will throw an error.

I don't think there is that much value in including the original sourcemaps in the library, since the code isn't even minified. So if there are no objections, I'll submit a PR which just removes them. The same issue also applies to the latest version of `dom-anchor-text-quote`.

**Comment by tilgovi** [comment]
I'm surprised. What tools complain? I can see the source maps fine in my browser. The source map format contains the original code inline, I thought. The "src" folder shouldn't need to be available.

**Comment by robertknight** [comment]
Indeed @tilgovi , you're quite right. I read an error message in a different context and jumped to the wrong conclusion.

**Comment by robertknight** [comment]
The issue turned out to be an old version of the `combine-source-map` library (used indirectly via proxyquireify) which couldn't handle the inline source maps in this package.

**Comment by tilgovi** [comment]
No worries. Open another if you do run into any problem with the packaging.
