### ISSUE TITLE
New fromRange implementation can give different outputs in Microsoft Edge and other browsers

### ISSUE THREAD

**Issue by robertknight** [tilgovi/dom-anchor-text-position#4]
Microsoft Edge and Internet Explorer have several bugs related to new lines in the return value of `Range.prototype.toString` which can lead to the [new implementation](https://github.com/tilgovi/dom-anchor-text-position/commit/d0d11e3630588e4f8b2dbddf5cc70d38b2491677) of `fromRange` returning values which are:

1. Different to the start/end positions for the same range returned in Chrome and Firefox
2. Inconsistent with the start/end positions for a given substring in `Node.textContent`. This causes the [dom-anchor-text-quote](https://github.com/tilgovi/dom-anchor-text-quote) library to return incorrect selectors. See https://github.com/tilgovi/dom-anchor-text-quote

Issues that I know of:

1. https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/110962/
2. Within `<pre>` elements, new lines are reported as `\r\n` instead of `\n` in `Range.toString()` [1]

[1] This prints the same value twice in Chrome/Firefox but different values in Edge:
```html
<html>
<body>
  <pre id="content">
    One
    Two
    Three
  </pre>
  <script>
    var preEl = document.getElementById('content');
    console.log('Text content length', preEl.textContent.length);

    var range = document.createRange();
    range.setStart(preEl, 0);
    range.setEnd(preEl,preEl.childNodes.length);
    console.log('Range content length', range.toString().length);
  </script>
  </body>
</html>
```

**Comment by robertknight** [comment]
Aside from this issue, the current version of the lib [does fix several issues](https://github.com/hypothesis/client/pull/159/files#diff-319dcadad4bcd56162c3a7007decce60) with anchoring seen in the Hypothesis client.

**Comment by tilgovi** [comment]
Wow! It's great to hear that it fixes issues. I'm super glad to hear it.

Do you have any ideas for fixes for Edge, or should we just let Edge address its own issues?

**Comment by robertknight** [comment]
> Do you have any ideas for fixes for Edge, or should we just let Edge address its own issues?

Internet Explorer 10/11 and Edge together account for about 6.5% of our users (based on latest numbers from GA), so we do need to address the issue.

I have a solution which uses a ponyfill for `Range.toString()`, based on the spec and Blink's implementation. PR forthcoming.

**Comment by robertknight** [comment]
Reported one of the issues upstream as https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10291116/
